### ISSUE TITLE
Problems in the source table

### ISSUE THREAD

**Issue by pasqLisena** [silknow/thesaurus#1]
Tab `Español` of the [source table](https://docs.google.com/spreadsheets/d/1gvaJZyBzc43eJrwCLfgLd0scqo1P1ymVEsrjEqbIDA4/edit#gid=918943493).

- [x] __ASSOCIATED TERMS.__ There are references to not existing terms
  - i.e. _16_ and _412_
- [x] __ASSOCIATED TERMS.__ There are plain text references instead of numbers
  - e.g. _grana, quermes, cochinilla, carmes_ (line 134) 
- [x] __TERM.__ There are conjunctions. Only 1 label per language can be the prefLabel
  - i.e. _Efecto de perdido por trama o efecto lanzado o efecto de trama lanzada_
- [x] __HIERARCHIES.__ What to do when the value is not an URI neither a Number?
  - e.g. _Physical Attributes Facet->Attributes and Properties (hierarchy name) (G) -> <attributes and properties by general type> (G) -> attributes (characteristics) (G)- > <weaving techniques> -acanalado_

**Comment by rtroncy** [comment]
@pasqLisena Can you provide the row numbers that cause problems?

**Comment by pasqLisena** [comment]
I slightly updated the first post.

Briefly:
- **ASSOCIATED TERMS.** You can easily search the values with the [filter view ](https://sites.google.com/a/york.ac.uk/workingwithdata/google-sheets/filter-views) of Google Sheet, knowing that:
  - the orphan references are only the values _16_ and _412_
  - the plain text references are visible at the bottom of the filter
- **TERM.** Only the example is involved in the issue. (id = 178)
- **HIERARCHIES.** This problem involves a lot of lines, but they are very visibles (long text with arrows `->` inside)

I could mark those cells with colors, but there is already some background set, I fair to mix up

**Comment by pasqLisena** [comment]
Closed in 90470b5
