### ISSUE TITLE
Display thesaurus metadata about authors in SKOSMOS

### ISSUE THREAD

**Issue by rtroncy** [silknow/thesaurus#10]
We have recently edited the authors of the SILKNOW Thesaurus in [this google doc](https://docs.google.com/document/d/1MWS82XuMjpY5dLR9QFOXLxPEn9CmnIDHjqpqd6KeA3U/edit).

This has been translated into [this turtle file](https://github.com/silknow/knowledge-base/blob/master/vocabularies/vocabulary/thesaurus-authors.ttl). I suppose that this turtle file has been loaded in the triple store. However, this metadata is **NOT** visualized in SKOSMOS at https://skosmos.silknow.org/thesaurus/en/. It should be made visible.

**Comment by pasqLisena** [comment]
I realised that the [URI](https://data.silknow.org/vocabulary/silk-thesaurus) of the thesaurus (where metadata is attached) was wrong (see https://github.com/silknow/knowledge-base/commit/45f113e3cee06e4166c27570a387225ef687010f).

@ehrhart can you please reupload it?
This may probably solve this issue

**Comment by ehrhart** [comment]
I have re-uploaded the file. Authors and contributors are now visible on https://skosmos.silknow.org/thesaurus/en/

**Comment by rtroncy** [comment]
Great! Can we also remove the <http://data.silknow.org/SILKNOW> in the list of Creator? I'm not sure where it comes from

**Comment by pasqLisena** [comment]
It was in the main thesaurus file. 
- Successfully removed with a DELETE query
- Removed that logic in https://github.com/silknow/thesaurus/commit/23580173841b715cfccbccfe28187013e681f2f3 for next time
