### ISSUE TITLE
Add links between thesaurus terms and Wikidata when the mappings will have been verified

### ISSUE THREAD

**Issue by rtroncy** [silknow/thesaurus#11]
Janez from JSI has produced a set of mappings between SILKNOW thesaurus terms and Wikidata, see https://lists.eurecom.fr/sympa/arc/silknow/2020-07/msg00008/silknow-matched-items.xlsx.

I'm asking Mar to validate those mappings and to characterize the nature of the relationships, e.g., should we represent them as `skos:exactMatch`?

**Comment by pasqLisena** [comment]
+1

Are we ok with the implementation or still waiting for validation?

**Comment by rtroncy** [comment]
We are waiting for the validation by the domain experts regarding the nature of the mapping to apply. See also [this thread](https://lists.eurecom.fr/sympa/arc/silknow/2021-01/msg00018.html).

**Comment by rtroncy** [comment]
@pasqLisena 
Characterization and validation of the mappings is now completed. Please, see https://docs.google.com/spreadsheets/d/18UGyio2nNC7O8PTZbX0FSTi-b0KCZ-5L/edit#.

Can you now export the graph that will materialize the semantic relationships between the SILKNOW terms and Wikidata?

**Comment by pasqLisena** [comment]
What about those `NoMatch`? Should I ignore those lines?

**Comment by rtroncy** [comment]
Yes, the `NoMatch` should be ignored.
