### ISSUE TITLE
Language-exclusive terms

### ISSUE THREAD

**Issue by pasqLisena** [silknow/thesaurus#13]
In thesaurus conversion, we always use the ID in Spanish, even for the other tabs.
This is for avoiding inconsistencies, e.g. in the French tab, [887 Lirio (es)	=> 792 Lis (fr)](https://docs.google.com/spreadsheets/d/1y5srx0Ao4QshoQ5zIdFHZpmBgctw3Q5sTSqTGo6xXfM/edit#gid=981766071&range=695:695).

However, I am noticing now some entries that are there only in some languages, but not in Spanish.
The two only cases are 816 and 301 (both only in fr and it).
The 816 also appears among [the Wikidata matches](https://docs.google.com/spreadsheets/d/18UGyio2nNC7O8PTZbX0FSTi-b0KCZ-5L/edit#gid=83637274&range=1783:1784).
(So this issue is blocking #11).

We need to know if those entries are correct or not.
In the positive case, we will use the language ID when the Spanish one is missing (I already checked that there are no id collisions).
In the negative case, we will continue to ignore them and they need to be removed from the Wikidata matches.

Last version of thesaurus: [2.4](https://docs.google.com/spreadsheets/d/1y5srx0Ao4QshoQ5zIdFHZpmBgctw3Q5sTSqTGo6xXfM)

**Comment by MarGaitan** [comment]
Hi Pasquale, 

Thanks for pointing out these issues. 

887- 792, it has the wrong ID in French. 

816 & 301 are terms that were deleted, actually, they became ID 855, we'll delete those in Fr and IT. And correct the ID in the latest release

**Comment by pasqLisena** [comment]
Thank you @MarGaitan !

So we will keep only the entries with an ID in the Spanish tab.
816 should be removed from the Wikidata matches
